lms/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
]

adminApp/models.py
from django.db import models


class Institue(models.Model):

    Name = models.CharField(max_length=60)
    Address = models.CharField(max_length=50)
    Contact = models.CharField(max_length=20)

    def __str__(self):
        return self.Name


class Department(models.Model):
    InstitueId = models.ForeignKey(Institue,verbose_name="Institute", on_delete=models.CASCADE)
    Name = models.CharField(max_length=60)
    Contact = models.CharField(max_length=20)

    def __str__(self):
        return self.Name


class Program(models.Model):
    Name = models.CharField("Program Name", max_length=20)
    DepartmentId = models.ForeignKey(Department,verbose_name="Department", on_delete=models.CASCADE)
    EntryTest = models.DateField("Entry Test")
    MeritList = models.DateField("Mert List")
    FeeSubmission = models.DateField("Fee Submission")
    ClassesCommence = models.DateField("Class Starts")

    def __str__(self):
        return self.Name

    class Meta:
        unique_together = (("Name", "DepartmentId"),)


class Lookup(models.Model):
    Value = models.CharField(max_length=20)
    Category = models.CharField(max_length=20)

    def __str__(self):
        return self.Value


class Class(models.Model):
    Name = models.CharField(max_length=20)
    DepartmentId = models.ForeignKey(Department,verbose_name="Department", on_delete=models.CASCADE)
    ProgramId = models.ForeignKey(Program, verbose_name="Program",on_delete=models.CASCADE)

    def __str__(self):
        return self.Name


class Section(models.Model):

    DepartmentId = models.ForeignKey(
        Department, verbose_name="Department", on_delete=models.CASCADE)
    ProgramId = models.ForeignKey(
        Program, verbose_name="Program", on_delete=models.CASCADE)
    SectionName = models.CharField("Section", max_length=20)
    ClassId = models.ForeignKey(
        Class, verbose_name="Class", on_delete=models.CASCADE)
    Strength = models.IntegerField()

    def __str__(self):
        return self.SectionName



class Person(models.Model):
    FirstName = models.CharField("First Name", max_length=20)
    LastName = models.CharField("Last Name", max_length=20)
    FatherName = models.CharField("Father Name", max_length=30)
    Cnic = models.CharField("CNIC/B-FORM", max_length=20, unique=True)
    Address = models.CharField("Permenant Address", max_length=50)
    Contact = models.CharField("Phone Number", max_length=20)
    Gender = models.ForeignKey(Lookup, on_delete=models.CASCADE)

    def __str__(self):
        return self.FirstName+' '+self.LastName


class Student(models.Model):
    ClassId = models.ForeignKey(
        Class, verbose_name="Class", on_delete=models.CASCADE)
    SectionId = models.ForeignKey(
        Section, verbose_name="Section", on_delete=models.CASCADE)
    DepartmentId = models.ForeignKey(
        Department, verbose_name="Department", on_delete=models.CASCADE)
    ProgramId = models.ForeignKey(
        Program, verbose_name="Program", on_delete=models.CASCADE)
    registrationNumber = models.CharField(
        "Registration Number", max_length=12, unique=True)
    monthlyFee = models.IntegerField()
    PersonId = models.ForeignKey(
        Person, verbose_name="Name", on_delete=models.CASCADE)

    def __str__(self):
        return self.registrationNumber


Employess_CHOICES = ((1, 'Chair Person'), (2, 'Associate Professor'),
                     (3, 'Asistant Professor'), (4, 'Professor'), (5, 'Clerk'))


class Employee(models.Model):
    DepartmentId = models.ForeignKey(
        Department, verbose_name="Department", on_delete=models.CASCADE)
    PersonId = models.ForeignKey(
        Person, verbose_name="Person", on_delete=models.CASCADE)
    Designation = models.IntegerField(choices=Employess_CHOICES)
    Salary = models.IntegerField("Monthly Salary")

    def __str__(self):
        return str(self.PersonId)


class Days(models.Model):
    DayName = models.CharField("Day of Week", max_length=10)
    DayNumber = models.IntegerField()

    def __str__(self):
        return self.DayName


class Calender(models.Model):
    date_Time = models.DateField("Date")

    def __str__(self):
        return self.date_Time


BOOL_CHOICES = ((True, 'Present'), (False, 'Absent'))


class Fine(models.Model):
    amount = models.IntegerField()
    personId = models.ForeignKey(Person, verbose_name="Person",on_delete=models.CASCADE)
    designation = models.ForeignKey(Lookup, on_delete=models.CASCADE)

    def __str__(self):
        return self.amount


class Subject(models.Model):
    Name = models.CharField(max_length=15)
    description = models.CharField(max_length=255)
    DepartmentId = models.ForeignKey(Department,verbose_name="Department", on_delete=models.CASCADE)

    def __str__(self):
        return self.Name


class Attendance(models.Model):
    Date = models.DateField()
    StudentId = models.ForeignKey(Student,verbose_name="Student", on_delete=models.CASCADE)
    SubjectId = models.ForeignKey(Subject, verbose_name="Subject",on_delete=models.CASCADE)
    status = models.BooleanField(choices=BOOL_CHOICES)

    def __str__(self):
        return str(self.Date)

    class Meta:
        unique_together = (("Date", "StudentId", "SubjectId"),)


class Exam(models.Model):

    Name = models.CharField(max_length=12)
    DepartmentId = models.ForeignKey(Department,verbose_name="Department", on_delete=models.CASCADE)
    ClassId = models.ForeignKey(Class, verbose_name="Class",on_delete=models.CASCADE)
    SectionId = models.ForeignKey(Section,verbose_name="Section", on_delete=models.CASCADE)
    SubjectId = models.ForeignKey(Subject,verbose_name="Subject", on_delete=models.CASCADE)
    totalMarks = models.IntegerField()
    weightage = models.IntegerField()
    startTime = models.DateTimeField()
    endTime = models.DateTimeField()

    def __str__(self):
        return self.Name



class Evaluation(models.Model):
    ExamId = models.ForeignKey(Exam, verbose_name="Exam",on_delete=models.CASCADE)
    obtainedMarks = models.IntegerField()
    Grade = models.CharField(max_length=2)
    StudentId = models.ForeignKey(Student, verbose_name="Student",on_delete=models.CASCADE)
    class Meta:
        unique_together = (( "ExamId", "StudentId"),)


class SubjectClass(models.Model):
    DepartmentId = models.ForeignKey(Department,verbose_name="Department", on_delete=models.CASCADE)
    ProgramId = models.ForeignKey(Program,verbose_name="Program", on_delete=models.CASCADE)
    ClassId = models.ForeignKey(Class, verbose_name="Class",on_delete=models.CASCADE)
    SubjectId = models.ForeignKey(Subject,verbose_name="Subject", on_delete=models.CASCADE)
    SemsterName = models.CharField(max_length=10)

    def __str__(self):
        return self.SubjectId.Name

    class Meta:
        unique_together = (("ClassId", "SubjectId", "SemsterName"),)


class SubjectTeacher(models.Model):
    SubjectId = models.ForeignKey(
        Subject, on_delete=models.CASCADE)
    TeacherId = models.ForeignKey(
        Employee, on_delete=models.CASCADE)
    SectionId = models.ForeignKey(Section, on_delete=models.CASCADE)


class Period(models.Model):
    startTime = models.TimeField()
    EndTime = models.TimeField()
    periodNumber = models.IntegerField(primary_key=True)


class Scheduale(models.Model):
    dayName = models.ForeignKey(Days, on_delete=models.CASCADE)
    periodNumber = models.ForeignKey(Period, on_delete=models.CASCADE)
    SubjectId = models.ForeignKey(Subject, on_delete=models.CASCADE)


class TimeTable(models.Model):
    SchedualeId = models.ForeignKey(Scheduale, on_delete=models.CASCADE)
    SubjectId = models.ForeignKey(Subject, on_delete=models.CASCADE)
    periodNumber = models.ForeignKey(Period, on_delete=models.CASCADE)
    TeacherId = models.ForeignKey(Employee, on_delete=models.CASCADE)
    SchedualeDateAndTime = models.ForeignKey(
        Calender, on_delete=models.CASCADE)

adminApp/forms.py
import datetime
from django.forms.widgets import HiddenInput
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import Person, Student, SubjectClass, Calender

from datetimepicker.widgets import DateTimePicker


class AddPersonForm(ModelForm):
    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance')
        if instance:
            self.base_fields['FirstName'].initial = instance.FirstName
            self.base_fields['LastName'].initial = instance.LastName
            self.base_fields['FatherName'].initial = instance.FatherName
            self.base_fields['Cnic'].initial = instance.Cnic
            self.base_fields['Address'].initial = instance.Address
            self.base_fields['Contact'].initial = instance.Contact
        forms.ModelForm.__init__(self, *args, **kwargs)
    FirstName = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'vTextField', 'required': True}))
    LastName = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'vTextField'}))
    FatherName = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'vTextField'}))
    Cnic = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'vTextField'}))
    Address = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'vTextField'}))
    Contact = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'vTextField'}))

    class Meta:
        model = Person
        fields = '__all__'


class AddStudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'


YEAR_CHOICES = ((1, 'Ist'), (2, '2nd'), (3, '3rd'), (4, '4th'),
                (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'))


class DateInput(forms.DateInput):
    input_type = 'date'


class DateForm(forms.ModelForm):

    class Meta:
        model = Calender
        fields = ['date_Time']
        widgets = {
            'date_Time': DateInput(),
        }


class AddClassSubjectForm(ModelForm):
    SemsterName = forms.ChoiceField(
        choices=YEAR_CHOICES, widget=forms.Select, label='Select Semster')

    class Meta:
        model = SubjectClass
        fields = '__all__'

adminApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
# Create your views here.
from django.http import HttpResponse
from .models import Student, Person
from django.contrib.auth.models import User

import json
from .forms import AddStudentForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def Add_Student(request):

    form = AddStudentForm()
    return render(request, 'adminApp/addStudent.html', {'form': form})

adminApp/templates/adminApp/EvaluationReport.html
<!doctype html>

<html>

<head>
    <meta charset="utf-8">
    <title>Evaluation Report</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }

        .table tbody+tbody {
            border-top: 2px solid #000;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }
    </style>
</head>

<body>

    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3>Evaluation Report</h3>
            </div>

            <div class="list-group">
                <p>Department:{{exam_data.DepartmentId}}
                    <p>Class: {{ exam_data.ClassId }} Section:{{exam_data.SectionId}} </p>
                    <p>Subject:{{exam_data.SubjectId}} Exam:{{exam_data}}</p>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>Student Name</th>
                        <th>Registartion Number</th>
                        <th>Marks</th>
                        <th>Grade</th>
                    </tr>
                </thead>
                <tbody>
                    {%for val in students%}
                    {%if val%}
                    {%for Marks in val%}
                    {%if Marks%}
                    <tr class="form-row">
                        <td>
                            {{Marks.StudentId.PersonId}}
                        </td>

                        <td>
                            {{Marks.StudentId.registrationNumber}}
                        </td>
                        <td>
                            {{Marks.obtainedMarks}}
                        </td>

                        <td>
                            {{Marks.Grade}}
                        </td>

                    </tr>
                    {% endif %}
                    {% endfor %}
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</body>

</html>

adminApp/templates/adminApp/StudentReport.html
<!doctype html>

<html>

<head>
    <meta charset="utf-8">
    <title>Students Report</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }

        .table tbody+tbody {
            border-top: 2px solid #000;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }
    </style>
</head>

<body>

    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3>Students Report</h3>
            </div>

            
            <div class="list-group">
                <p>Department:{{DepartmentId}} Class: {{ classId }}  </p>
                <p>Section:{{SectionId}}  </p>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Registration Number</th>
                    </tr>
                </thead>
                <tbody>
                    {%for val in students%}
                    {%if val%}
                    <tr>
                        <td>{{val.PersonId}}</td>
                        <td>{{val.registrationNumber}}</td>
                        
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</body>

</html>

adminApp/templates/adminApp/addClassSubject.html
{% extends "admin/base_site.html" %}

{% block breadcrumbs %}
{% endblock %}
{%load crispy_forms_tags%}
{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Learning Managemnet System</a></h1>
{% endblock %}
{% block content %}
<div>
    <form action="{% url 'admin:adminApp_class_subject' class_id%}" method='post'>
        
        <fieldset class="module aligned">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-row field">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>

            {% endfor %}

            <button type="submit" class="btn btn-secondary mb-2">Add</button>


        </fieldset>
    </form>
</div>
{% endblock %}

adminApp/templates/adminApp/addEmployes.html
{% extends "admin/change_form.html" %}

{% block breadcrumbs %}
{% endblock %}
{%load crispy_forms_tags%}
{% block field_sets %}
<form >
    <fieldset class="module aligned">
        
        {% csrf_token %}
        {% for field in form %}
        <div class="form-row field">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        {{block.super}}

    </fieldset>
</form>

{% endblock %}

adminApp/templates/adminApp/addStudent.html
{% extends "admin/change_form.html" %}

{%load crispy_forms_tags%}
{% block field_sets %}
<form >
    <fieldset class="module aligned">
        {% csrf_token %}
        <div class="form-row field-Classid">
            <div>
                <label class="required" for="id FirstName">
                    First Name
                </label>
                <input id="id_FirstName" class="vTextField" type="text" name="FirstName" required="">
            </div>
        </div>
        <div class="form-row field-LastName">
            <div>
                <label class="required" for="id LastName">
                    Last Name
                </label>
                <input id="id_LastName" class="vTextField" type="text" name="LastName" required="">
            </div>
        </div>
        <div class="form-row field-FatherName">
            <div>
                <label class="required" for="id FatherName">
                    Father Name
                </label>
                <input id="id_fatherName" class="vTextField" type="text" name="FatherName" required="">
            </div>
        </div>
        <div class="form-row field-Cnic">
            <div>
                <label class="required" for="id Cnic">
                    Cnic
                </label>
                <input id="id_Cnic" class="vTextField" type="text" name="Cnic" required="">
            </div>
        </div>
        <div class="form-row field-Contact">
            <div>
                <label class="required" for="id Contact">
                    Contact
                </label>
                <input id="id_Cnic" class="vTextField" type="text" name="Contact" required="">
            </div>
        </div>
        <div class="form-row field-Address">
            <div>
                <label class="required" for="id Address">
                    Address
                </label>
                <input id="id_Address" class="vTextField" type="text" name="Address" required="">
            </div>
        </div>

        {{block.super}}

    </fieldset>
</form>

{% endblock %}

adminApp/templates/adminApp/addSubjectTeacher.html
{% extends "admin/change_form.html" %}

{% block breadcrumbs %}
{% endblock %}
{%load crispy_forms_tags%}
{% block field_sets %}
<form>
    <fieldset class="module aligned">

        <tr class="form-row">
            <td>
                
                {{val.SubjectId}}

            </td>
        </tr>
            {{block.super}}

    </fieldset>
</form>

{% endblock %}

adminApp/templates/adminApp/attendanceDetailReport.html
<!doctype html>

<html>

<head>
    <meta charset="utf-8">
    <title>Attendance Report</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }

        .table tbody+tbody {
            border-top: 2px solid #000;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }
    </style>
</head>

<body>

    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3>Attendance Report - {{ attendancedate | date:"d/m/Y" }}</h3>
            </div>

            <div class="list-group">
                <p>Class: {{ classId }} Semster:{{SemsterName}} </p>
                <p>Section:{{SectionId}} Subject:{{subjectId}}</p>
                <p>Total Present :{{totalPresent}}</p>
                <p> Total Absent :{{totalAbsent}}</p>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Registration Number</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {%for val in details%}
                    {%if val%}
                    <tr>
                        <td>{{val.StudentId.PersonId}}</td>
                        <td>{{val.StudentId.registrationNumber}}</td>
                        <td>
                            {% if val.status %}
                            Present
                            {% else %}
                            Absent
                            {% endif %}
                        </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</body>

</html>

adminApp/templates/adminApp/changeSection.html
{% extends "admin/change_form.html" %}

{% block field_sets %}

{% block breadcrumbs %}
{% endblock %}
{{block.super}}
<div>
    <fieldset class="module">

        <h2>Students</h2>

        <table id="student_list">
            <thead>
                <tr>
                    <th class="sortable column-registrationNumber" scope="col">
                        <div class="text">
                            <a>Registration Number</a>
                        </div>
                        <div class="clear">

                        </div>
                    </th>
                    <th class="sortable column-PersonId" scope="col">
                        <div class="text">
                            <a>Name</a>
                        </div>
                        <div class="clear">

                        </div>
                    </th>

                </tr>
            </thead>
            <tbody>
                {% for val in osm_data  %}
                {% if val %}
                <tr class="row">
                    <th class="field-registrationNumber">
                        <a href="{% url 'admin:adminApp_student_change' val.id %}"> {{val.registrationNumber}}</a>
                    </th>
                    <td class="field-PersonId">

                        {{val.PersonId}}

                    </td>
                </tr>
                {% endif %}

                {% endfor %}
                <tr class="add-row">
                    <td>
                        <a href="{% url 'admin:adminApp_student_add' %}">add another Student</a>
                    </td>
                </tr>
                <tr class="add-row">
                    <td>
                        <a href="{% url 'admin:adminApp_section_student_pdf' section_id %}">Generate Student List</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </fieldset>
    <fieldset class="module">

        <h2>Attendance</h2>

        <tr class="add-row">
            <td>
                <a href="{% url 'admin:adminApp_section_semster_list' section_id %}">Mark Attendance</a>
            </td>
        </tr>
    </fieldset>
    <fieldset class="module">

        <h2>Evaluation</h2>
        <table id="student_list">
            <thead>
                <tr>
                    <th class="sortable column-registrationNumber" scope="col">
                        <div class="text">
                            <a>Exam Name</a>
                        </div>
                    </th>

                </tr>
            </thead>
            <tbody>
                {% for val in evaluations  %}
                {% if val %}
                <tr class="row">
                    <td>

                        <a href="{% url 'admin:adminApp_section_evaluation' val.id %}"> {{val.Name}}</a>


                    </td>
                </tr>
                {% endif %}

                {% endfor %}
                <tr class="add-row">
                    <td>
                        <a href="{% url 'admin:adminApp_exam_add' %}">add another Exam</a>
                    </td>
                </tr>

            </tbody>
        </table>
    </fieldset>
</div>

{% endblock %}

adminApp/templates/adminApp/changeStudent.html
{% extends "admin/change_form.html" %}

{% block breadcrumbs %}
{% endblock %}
{%load crispy_forms_tags%}
{% block field_sets %}
<form>
    <fieldset class="module aligned">
        {% for field in form %}
        <div class="form-row field">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        {{block.super}}

    </fieldset>

</form>
{% endblock %}

adminApp/templates/adminApp/markAttendance.html
{% extends "admin/base_site.html" %}

{% block breadcrumbs %}
{% endblock %}
{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Learning Managemnet System</a></h1>
{% endblock %}
{% block content %}
<fieldset class="module">

    <form class="form-inline" action="{% url 'admin:adminApp_section_attendance' SectionId semsterId  subjectId %}"
        method='post'>
        {% csrf_token %}
        <h2>Attendacce</h2>

        <a href="{% url 'admin:adminApp_subject_attendance' SectionId semsterId  subjectId %}">View
            Attendance</a>

        <h4>Class:{{classId}}</h4>
        <h4>Section:{{SectionId}}</h4>
        {{ dateForm }}

        <table>
            <thead>
                <tr>
                    <td>
                        <h4>Student Name</h4>
                    </td>

                    <td>
                        <h4> Registartion Number</h4>
                    </td>
                    <td>
                        <h4> Status</h4>
                    </td>
                </tr>
            </thead>
            <tbody>
                {%for val in students%}
                {%if val%}
                <tr>
                    <td>
                        {{val.PersonId}}
                    </td>

                    <td>
                        {{val.registrationNumber}}
                    </td>
                    <td>
                        <input type="checkbox" name={{val.registrationNumber}}>
                    </td>
                </tr>
                {%endif %}
                {%endfor%}

            </tbody>



        </table>
        <button type="submit" class="btn btn-secondary mb-2">Add</button>
    </form>
</fieldset>
{% endblock %}

adminApp/templates/adminApp/markEvaluation.html
{% extends "admin/base_site.html" %}

{% block breadcrumbs %}
{% endblock %}
{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Learning Managemnet System</a></h1>
{% endblock %}
{% block content %}
<fieldset class="module">

    <form class="form-inline" action="" method='post'>
        {% csrf_token %}
        <h2>Evaluation</h2>


        <h4>Depertment:{{exam_data.DepartmentId}}</h4>
        <h4>Class:{{exam_data.ClassId}}</h4>
        <h4>Section:{{exam_data.SectionId}}</h4>
        <h4>Subject:{{exam_data.SubjectId}}</h4>
        <h4>Exam:{{exam_data}}</h4>

        <table>
            <thead>
                <tr>
                    <td>
                        <h4>Student Name</h4>
                    </td>

                    <td>
                        <h4> Registartion Number</h4>
                    </td>
                    <td>
                        <h4> Marks</h4>
                    </td>
                </tr>
            </thead>
            <tbody>
                {%for val in students%}
                {%if val%}
                <tr>
                    <td>
                        {{val.PersonId}}
                    </td>

                    <td>
                        {{val.registrationNumber}}
                    </td>
                    <td>
                        <input type="text" name={{val.registrationNumber}}>
                    </td>
                </tr>
                {%endif %}
                {%endfor%}
            </tbody>
        </table>
        <button type="submit" class="btn btn-secondary mb-2">Mark</button>
    </form>
</fieldset>
{% endblock %}

adminApp/templates/adminApp/sectionSemster.html
{% extends "admin/base_site.html" %}
{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Learning Managemnet System</a></h1>
{% endblock %}

{% block breadcrumbs %}
{% endblock %}
{% block content %}
<fieldset class="module">
    <h2>Semsters</h2>
    <table>
        <tr class="form-row">
            <td>
                <a href="{% url 'admin:adminApp_section_subjects' SectionId 1 %}">Ist Semster</a>
            </td>
        </tr>
        <tr class="form-row">
            <td>
                <a href="{% url 'admin:adminApp_section_subjects' SectionId 2 %}">2nd Semster</a>
            </td>
        </tr>
        <tr class="form-row">
            <td>
                <a href="{% url 'admin:adminApp_section_subjects' SectionId 3 %}">3rd Semster</a>
            </td>
        </tr>
        <tr class="form-row">
            <td>
                <a href="{% url 'admin:adminApp_section_subjects' SectionId 4 %}">4th Semster</a>
            </td>
        </tr>
        <tr class="form-row">
            <td>
                <a href="{% url 'admin:adminApp_section_subjects' SectionId 5 %}">5th Semster</a>
            </td>
        </tr>
        <tr class="form-row">
            <td>
                <a href="{% url 'admin:adminApp_section_subjects' SectionId 6 %}">6th Semster</a>
            </td>
        </tr>
        <tr class="form-row">
            <td>
                <a href="{% url 'admin:adminApp_section_subjects' SectionId 7 %}">7th Semster</a>
            </td>
        </tr>
        <tr class="form-row">
            <td>

                <a href="{% url 'admin:adminApp_section_subjects' SectionId 8 %}">8th Semster</a>
            </td>
        </tr>
    </table>
</fieldset>
{% endblock %}